### ISSUE TITLE
Why are the images in emps/segmaps/ are empty (black)?

### ISSUE THREAD

**Issue by hamedmh** [by256/emps#2]
Hi,
Thanks for this valuable dataset.
I noticed that the images in  emps/segmaps/  are empty (black, when clicking on them).
Am I missing something?
Best regards,
Hamed

**Comment by by256** [comment]
Hi Hamed,

Please see this issue for clarification on this: https://github.com/by256/emps/issues/1

Batuhan

**Comment by hamedmh** [comment]
Thanks!
