### ISSUE TITLE
how to visualize balck segmap?

### ISSUE THREAD

**Issue by luoolu** [by256/emps#4]
how to visualize the color instance of the segmap

**Comment by by256** [comment]
This closed issue might be of use: https://github.com/by256/emps/issues/1

The segmaps are 32 bit integer images so opening them with a standard image viewer probably won't work. I usually load them with PIL and visualize them with matplotlib using a discrete colormap. Avoid using cv2 to load the images as opencv converts images to 8 bit int images by default.
